// Generated by jextract

package ffi.ort;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OrtEpFactory {
 *     uint32_t ort_version_supported;
 *     const char *(*GetName)(const OrtEpFactory *);
 *     const char *(*GetVendor)(const OrtEpFactory *);
 *     OrtStatus *(*GetSupportedDevices)(OrtEpFactory *, const OrtHardwareDevice *const *, size_t, OrtEpDevice **, size_t, size_t *);
 *     OrtStatus *(*CreateEp)(OrtEpFactory *, const OrtHardwareDevice *const *, const OrtKeyValuePairs *const *, size_t, const OrtSessionOptions *, const OrtLogger *, OrtEp **);
 *     void (*ReleaseEp)(OrtEpFactory *, struct OrtEp *);
 * }
 * }
 */
public class OrtEpFactory {

    OrtEpFactory() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        onnxruntime_c_api_h.C_INT.withName("ort_version_supported"),
        MemoryLayout.paddingLayout(4),
        onnxruntime_c_api_h.C_POINTER.withName("GetName"),
        onnxruntime_c_api_h.C_POINTER.withName("GetVendor"),
        onnxruntime_c_api_h.C_POINTER.withName("GetSupportedDevices"),
        onnxruntime_c_api_h.C_POINTER.withName("CreateEp"),
        onnxruntime_c_api_h.C_POINTER.withName("ReleaseEp")
    ).withName("OrtEpFactory");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ort_version_supported$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ort_version_supported"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final OfInt ort_version_supported$layout() {
        return ort_version_supported$LAYOUT;
    }

    private static final long ort_version_supported$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static final long ort_version_supported$offset() {
        return ort_version_supported$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static int ort_version_supported(MemorySegment struct) {
        return struct.get(ort_version_supported$LAYOUT, ort_version_supported$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ort_version_supported
     * }
     */
    public static void ort_version_supported(MemorySegment struct, int fieldValue) {
        struct.set(ort_version_supported$LAYOUT, ort_version_supported$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * const char *(*GetName)(const OrtEpFactory *)
     * }
     */
    public static class GetName {

        GetName() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(GetName.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(GetName.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout GetName$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GetName"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *(*GetName)(const OrtEpFactory *)
     * }
     */
    public static final AddressLayout GetName$layout() {
        return GetName$LAYOUT;
    }

    private static final long GetName$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *(*GetName)(const OrtEpFactory *)
     * }
     */
    public static final long GetName$offset() {
        return GetName$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *(*GetName)(const OrtEpFactory *)
     * }
     */
    public static MemorySegment GetName(MemorySegment struct) {
        return struct.get(GetName$LAYOUT, GetName$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *(*GetName)(const OrtEpFactory *)
     * }
     */
    public static void GetName(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GetName$LAYOUT, GetName$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * const char *(*GetVendor)(const OrtEpFactory *)
     * }
     */
    public static class GetVendor {

        GetVendor() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(GetVendor.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(GetVendor.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout GetVendor$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GetVendor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *(*GetVendor)(const OrtEpFactory *)
     * }
     */
    public static final AddressLayout GetVendor$layout() {
        return GetVendor$LAYOUT;
    }

    private static final long GetVendor$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *(*GetVendor)(const OrtEpFactory *)
     * }
     */
    public static final long GetVendor$offset() {
        return GetVendor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *(*GetVendor)(const OrtEpFactory *)
     * }
     */
    public static MemorySegment GetVendor(MemorySegment struct) {
        return struct.get(GetVendor$LAYOUT, GetVendor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *(*GetVendor)(const OrtEpFactory *)
     * }
     */
    public static void GetVendor(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GetVendor$LAYOUT, GetVendor$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatus *(*GetSupportedDevices)(OrtEpFactory *, const OrtHardwareDevice *const *, size_t, OrtEpDevice **, size_t, size_t *)
     * }
     */
    public static class GetSupportedDevices {

        GetSupportedDevices() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3, long _x4, MemorySegment _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(GetSupportedDevices.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(GetSupportedDevices.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, long _x2, MemorySegment _x3, long _x4, MemorySegment _x5) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout GetSupportedDevices$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("GetSupportedDevices"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatus *(*GetSupportedDevices)(OrtEpFactory *, const OrtHardwareDevice *const *, size_t, OrtEpDevice **, size_t, size_t *)
     * }
     */
    public static final AddressLayout GetSupportedDevices$layout() {
        return GetSupportedDevices$LAYOUT;
    }

    private static final long GetSupportedDevices$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatus *(*GetSupportedDevices)(OrtEpFactory *, const OrtHardwareDevice *const *, size_t, OrtEpDevice **, size_t, size_t *)
     * }
     */
    public static final long GetSupportedDevices$offset() {
        return GetSupportedDevices$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatus *(*GetSupportedDevices)(OrtEpFactory *, const OrtHardwareDevice *const *, size_t, OrtEpDevice **, size_t, size_t *)
     * }
     */
    public static MemorySegment GetSupportedDevices(MemorySegment struct) {
        return struct.get(GetSupportedDevices$LAYOUT, GetSupportedDevices$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatus *(*GetSupportedDevices)(OrtEpFactory *, const OrtHardwareDevice *const *, size_t, OrtEpDevice **, size_t, size_t *)
     * }
     */
    public static void GetSupportedDevices(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(GetSupportedDevices$LAYOUT, GetSupportedDevices$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * OrtStatus *(*CreateEp)(OrtEpFactory *, const OrtHardwareDevice *const *, const OrtKeyValuePairs *const *, size_t, const OrtSessionOptions *, const OrtLogger *, OrtEp **)
     * }
     */
    public static class CreateEp {

        CreateEp() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            MemorySegment apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_LONG,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(CreateEp.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(CreateEp.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, long _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6) {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout CreateEp$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("CreateEp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OrtStatus *(*CreateEp)(OrtEpFactory *, const OrtHardwareDevice *const *, const OrtKeyValuePairs *const *, size_t, const OrtSessionOptions *, const OrtLogger *, OrtEp **)
     * }
     */
    public static final AddressLayout CreateEp$layout() {
        return CreateEp$LAYOUT;
    }

    private static final long CreateEp$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OrtStatus *(*CreateEp)(OrtEpFactory *, const OrtHardwareDevice *const *, const OrtKeyValuePairs *const *, size_t, const OrtSessionOptions *, const OrtLogger *, OrtEp **)
     * }
     */
    public static final long CreateEp$offset() {
        return CreateEp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OrtStatus *(*CreateEp)(OrtEpFactory *, const OrtHardwareDevice *const *, const OrtKeyValuePairs *const *, size_t, const OrtSessionOptions *, const OrtLogger *, OrtEp **)
     * }
     */
    public static MemorySegment CreateEp(MemorySegment struct) {
        return struct.get(CreateEp$LAYOUT, CreateEp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OrtStatus *(*CreateEp)(OrtEpFactory *, const OrtHardwareDevice *const *, const OrtKeyValuePairs *const *, size_t, const OrtSessionOptions *, const OrtLogger *, OrtEp **)
     * }
     */
    public static void CreateEp(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(CreateEp$LAYOUT, CreateEp$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*ReleaseEp)(OrtEpFactory *, struct OrtEp *)
     * }
     */
    public static class ReleaseEp {

        ReleaseEp() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            onnxruntime_c_api_h.C_POINTER,
            onnxruntime_c_api_h.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = onnxruntime_c_api_h.upcallHandle(ReleaseEp.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ReleaseEp.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ReleaseEp$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ReleaseEp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*ReleaseEp)(OrtEpFactory *, struct OrtEp *)
     * }
     */
    public static final AddressLayout ReleaseEp$layout() {
        return ReleaseEp$LAYOUT;
    }

    private static final long ReleaseEp$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*ReleaseEp)(OrtEpFactory *, struct OrtEp *)
     * }
     */
    public static final long ReleaseEp$offset() {
        return ReleaseEp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*ReleaseEp)(OrtEpFactory *, struct OrtEp *)
     * }
     */
    public static MemorySegment ReleaseEp(MemorySegment struct) {
        return struct.get(ReleaseEp$LAYOUT, ReleaseEp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*ReleaseEp)(OrtEpFactory *, struct OrtEp *)
     * }
     */
    public static void ReleaseEp(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ReleaseEp$LAYOUT, ReleaseEp$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

